#!/usr/bin/env node
/*
  Static page generator.

  Reads the registry in /data/profiles.js and the markup in /src/template.html
  and writes one pre-rendered page per profile, plus the root page and the 404
  fallback. Generated files start with a marker comment; anything else in the
  repository is left untouched.

  Usage:
    node tools/build.mjs           # write the pages
    node tools/build.mjs --check   # fail if the committed pages are stale
*/

import { readFile, writeFile, mkdir, rm, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PROFILES, DEFAULT_SLUG } from "../data/profiles.js";
import { SITE } from "../src/config.js";
import { buildViewModel } from "../src/render.js";
import { escapeHtml } from "../src/utils.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
export const MARKER = "<!-- generated by tools/build.mjs -->";
const TEMPLATE_PATH = path.join(ROOT, "src", "template.html");
const RESERVED = new Set(["src", "data", "assets", "docs", "tools", "tests", "node_modules", ".git", ".github"]);

export function render(template, view, slug) {
  const tokens = {
    LANG: view.lang,
    SITE_NAME: escapeHtml(SITE.name),
    PROFILE_SLUG: slug,
    THEME_COLOR: view.themeColor,
    ROBOTS: view.robots,
    TITLE: escapeHtml(view.title),
    DESCRIPTION: escapeHtml(view.description),
    CANONICAL: escapeHtml(view.canonical),
    SHARE_IMAGE: escapeHtml(view.shareImage),
    /* JSON is injected inside a <script>, so "<" must not appear literally. */
    SCHEMA: view.schema.replace(/</g, "\\u003c"),
    THEME_STYLE: view.themeStyle,
    NAME: escapeHtml(view.name),
    HANDLE: escapeHtml(view.handle),
    AVATAR: escapeHtml(view.avatar),
    AVATAR_ALT: escapeHtml(view.avatarAlt),
    LOCATION: escapeHtml(view.location),
    LOCATION_HIDDEN: view.locationHidden,
    BIO: escapeHtml(view.bio),
    BIO_HIDDEN: view.bioHidden,
    SOCIAL: view.socialHtml,
    FEATURED: view.featuredHtml,
    LINKS: view.linksHtml,
    EMPTY_NOTES: escapeHtml(view.emptyNotes),
    /* Shell copy, resolved from the profile language by src/i18n.js. */
    SHARE_LABEL: escapeHtml(view.strings.shareLabel),
    VERIFIED_LABEL: escapeHtml(view.strings.verifiedLabel),
    SOCIAL_LABEL: escapeHtml(view.strings.socialLabel),
    SCROLL_CUE_LABEL: escapeHtml(view.strings.scrollCueLabel),
    LINKS_LABEL: escapeHtml(view.strings.linksLabel),
    UPDATES_LABEL: escapeHtml(view.strings.updatesLabel),
    SECTION_KICKER: escapeHtml(view.strings.sectionKicker),
    TABS_LABEL: escapeHtml(view.strings.tabsLabel),
    TAB_NOTES: escapeHtml(view.strings.tabNotes),
    TAB_MEDIA: escapeHtml(view.strings.tabMedia),
    EMPTY_TITLE: escapeHtml(view.strings.emptyTitleNotes),
    FOOTER_NOTE: escapeHtml(view.strings.footerNote),
    AGE_CLOSE_LABEL: escapeHtml(view.strings.ageCloseLabel),
    AGE_EYEBROW: escapeHtml(view.strings.ageEyebrow),
    AGE_TITLE: escapeHtml(view.strings.ageTitle),
    AGE_COPY: escapeHtml(view.strings.ageCopy),
    AGE_CANCEL: escapeHtml(view.strings.ageCancel),
    AGE_CONTINUE: escapeHtml(view.strings.ageContinue),
  };

  const missing = new Set();
  const html = template.replace(/\{\{([A-Z_]+)\}\}/g, (match, key) => {
    if (key in tokens) return tokens[key];
    missing.add(key);
    return match;
  });
  if (missing.size) throw new Error(`template tokens with no value: ${[...missing].join(", ")}`);

  return `${MARKER}\n${html}`;
}

export function renderSitemap() {
  const urls = [
    `<url>\n    <loc>${SITE.origin}/</loc>\n  </url>`,
    ...Object.keys(PROFILES).map((slug) => `<url>\n    <loc>${SITE.origin}/${slug}</loc>\n  </url>`),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>\n${MARKER}\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  ${urls.join("\n  ")}\n</urlset>\n`;
}

export function plan(template) {
  const pages = new Map();
  const root = buildViewModel(PROFILES[DEFAULT_SLUG], { slug: DEFAULT_SLUG, path: "/" });
  pages.set("index.html", render(template, root, DEFAULT_SLUG));

  const fallback = buildViewModel(PROFILES[DEFAULT_SLUG], { slug: DEFAULT_SLUG, path: "/", robots: "noindex,follow" });
  pages.set("404.html", render(template, fallback, DEFAULT_SLUG));

  for (const [slug, profile] of Object.entries(PROFILES)) {
    const view = buildViewModel(profile, { slug, path: `/${slug}` });
    pages.set(`${slug}/index.html`, render(template, view, slug));
  }

  pages.set("sitemap.xml", renderSitemap());
  return pages;
}

async function staleDirectories(slugs) {
  const entries = await readdir(ROOT, { withFileTypes: true });
  const stale = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || RESERVED.has(entry.name) || entry.name.startsWith(".") || slugs.has(entry.name)) continue;
    try {
      const page = await readFile(path.join(ROOT, entry.name, "index.html"), "utf8");
      if (page.startsWith(MARKER)) stale.push(entry.name);
    } catch {
      /* not a generated profile folder */
    }
  }
  return stale;
}

async function main() {
  const check = process.argv.includes("--check");
  const template = await readFile(TEMPLATE_PATH, "utf8");
  const pages = plan(template);
  const problems = [];

  for (const [relative, content] of pages) {
    const target = path.join(ROOT, relative);
    if (check) {
      const current = await readFile(target, "utf8").catch(() => null);
      if (current !== content) problems.push(relative);
      continue;
    }
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
    console.log(`  wrote ${relative}`);
  }

  const stale = await staleDirectories(new Set(Object.keys(PROFILES)));
  for (const name of stale) {
    if (check) {
      problems.push(`${name}/ (profile no longer in the registry)`);
      continue;
    }
    await rm(path.join(ROOT, name), { recursive: true, force: true });
    console.log(`  removed stale ${name}/`);
  }

  if (check && problems.length) {
    console.error(`\n${problems.length} generated file(s) out of date:\n  ${problems.join("\n  ")}\nRun: npm run build`);
    process.exit(1);
  }

  console.log(check
    ? `ok: ${pages.size} generated page(s) up to date`
    : `built ${pages.size} page(s) for ${Object.keys(PROFILES).length} profile(s) on ${SITE.origin}`);
}

/* Only run as a CLI; the test suite imports render()/plan() directly. */
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
